### ISSUE TITLE
评论关联失败

### ISSUE THREAD

**Issue by inkss** [ArtalkJS/Artransfer#1]
较早期（当时使用的估计是 valine 吧）的数据都没有层级上的关联，数据库中 rid 为 0。

<details><summary>截图</summary><p>

![](https://user-images.githubusercontent.com/31947043/165046602-393f5aa5-7a59-42f9-a0c6-fd3a43e1983c.png)
![](https://user-images.githubusercontent.com/31947043/165046740-21856df0-157a-4059-a713-ecfb073e85ac.png)
![](https://user-images.githubusercontent.com/31947043/165046806-eedfb803-d9d8-4cd5-b58f-05793dd96776.png)

</p></details>

<details><summary>相关导出文件</summary><p>

分享链接：https://cloud.adc.ink/#s/8DvX_pFQ
访问密码：Om3Qo

</p></details>

**Comment by qwqcode** [comment]
你的 ArtalkGo 版本是多少，v2.1.3，pg 数据库，没有这个bug

![image](https://user-images.githubusercontent.com/22412567/165051902-0e723db6-6835-4c57-a188-4cb2e872066f.png)

**Comment by qwqcode** [comment]
我知道了，

![image](https://user-images.githubusercontent.com/22412567/165052488-f7a8f570-4676-460a-943b-92f4e6e1e90e.png)

**Comment by qwqcode** [comment]
这是 Artransfer 转换的 Bug，Valine 字段格式太多变了

**Comment by qwqcode** [comment]
怎么这个源数据，有些是 `"_id":"18ed09686197855406294998283743d2",` 有些是 `"_id":{"$oid":"5f7fd2a66cec66034553b4f2"}`

就挺怪

**Comment by qwqcode** [comment]
你是 Valine 转 Twikoo 转 Artalk 吗？

我推断有几种可能：

1. 这是腾讯云导出的 BUG，有的 `_id` 是 Object 类型
2. 是 Valine 转 Twikoo 时候部分 id 转换没对
3. 是 Twikoo 保存数据的时候 `_id` 有的保存为了 Object 类型

**Comment by inkss** [comment]
很奇怪

![](https://user-images.githubusercontent.com/31947043/165056856-eac86ab1-89a2-4039-929b-58ac29ce60fa.png)

**Comment by inkss** [comment]
我先用vscode全局替换掉吧

**Comment by qwqcode** [comment]
解决了
![image](https://user-images.githubusercontent.com/22412567/165057723-4e1d234f-0079-4954-9fd4-06defba9d110.png)

https://github.com/ArtalkJS/Artransfer/commit/c5613f106fd7a07e71fda4f748e0dfa5f9d21a74

**Comment by qwqcode** [comment]
把回复标签也删掉了

你可以用 https://artransfer.netlify.app/ 重新转换下

**Comment by inkss** [comment]
行，好的

**Comment by inkss** [comment]
感谢 ╰(*°▽°*)╯
