### ISSUE TITLE
转换WordPress遇到TypeError错误

### ISSUE THREAD

**Issue by liufeng** [ArtalkJS/Artransfer#4]
点击下载 Artrans 按钮，弹出窗口，窗口标题为artransfer.netlify.app，内容是TypeError: e.comment.forEach is not a function

我上传的文件是在WordPress控制台里，通过工具——导出——选择“所有内容”——点击“下载导出的文件”按钮这个过程导出的xml文件，不知道是不是我理解有误。

**Comment by zhecydn** [comment]
我和你一样，也是这个问题

**Comment by bibicadotnet** [comment]
`TypeError: e.comment.forEach is not a function`

Is the author still updating on Artransfer?

**Comment by qwqcode** [comment]
不好意思我遗漏了这个 issue，已查明当 WordPress 某个页面只有一条评论时会发生问题，目前已修复该问题，感谢反馈！！

---

I apologize for the oversight. We have identified an issue occurring when a WordPress page contains only one comment. This problem has been rectified. Thank you very much for bringing it to our attention!

Refer to: #5
